#!/usr/bin/env python3
"""Plot results from SimpleBoilerTest simulation

This script generates plots from the SimpleBoilerTest model simulation results.
It reads the MAT file generated by OpenModelica and creates visualization plots
showing boiler performance, temperatures, flow rates, and pressure.

Usage:
    python plot_simple_boiler.py [path_to_results.mat]
    
If no path is provided, it looks for the MAT file in the build directory.
"""

import sys
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
from scipy import io
from DyMat import DyMatFile

# Find the MAT file
if len(sys.argv) > 1:
    mat_file = Path(sys.argv[1])
    if not mat_file.exists():
        print(f"Error: MAT file not found: {mat_file}")
        sys.exit(1)
else:
    # Look in build directory (workspace root/build)
    build_dir = Path(__file__).parent.parent.parent / "build"
    mat_file = list(build_dir.glob("*SimpleBoilerTest*.mat"))
    if not mat_file:
        print("Error: Could not find results MAT file")
        print(f"Looking in: {build_dir}")
        print("Usage: python plot_simple_boiler.py [path_to_results.mat]")
        sys.exit(1)
    mat_file = mat_file[0]

print(f"Reading results from: {mat_file}")

# Read the MAT file
d = DyMatFile(str(mat_file))

# Get time vector - use scipy.io to read directly from MAT file
# Time is stored in data_2[0, :]
mat_dict = io.loadmat(str(mat_file), squeeze_me=False)
time = mat_dict['data_2'][0, :]  # Time is first row of data_2

# Extract signals
try:
    enable = d.data("boiler.enable")
    Q_actual = d.data("boiler.Q_actual") / 1000  # Convert W to kW
    T_inlet_C = d.data("boiler.T_inlet") - 273.15  # Convert K to °C
    T_outlet_C = d.data("boiler.T_outlet") - 273.15  # Convert K to °C
    # Convert to Fahrenheit
    T_inlet = T_inlet_C * 9/5 + 32
    T_outlet = T_outlet_C * 9/5 + 32
    m_flow_kg_s = d.data("boiler.m_flow")  # Mass flow in kg/s (output connector)
    p_PSI = d.data("boiler.p_PSI")
    # Get high limit trip status from model
    try:
        highLimitTripped_model = d.data("boiler.highLimitTripped")
    except:
        highLimitTripped_model = None
        print("Note: Could not find boiler.highLimitTripped output, using calculated value")
    
    # Get control signals (initialize to None first)
    setpointOK = None
    highLimitOK = None
    minimumRunTimeOK = None
    boilerActualEnable = None
    
    try:
        setpointOK = d.data("boiler.setpointController.setpointOK")
        highLimitOK = d.data("boiler.highLimitController.highLimitOK")
        minimumRunTimeOK = d.data("boiler.minimumRunTimeController.minimumRunTimeOK")
        boilerActualEnable = d.data("boiler.boilerEnableLogic.y")  # Final enable signal
    except:
        # Try alternative paths or use None
        try:
            setpointOK = d.data("boiler.setpointController.setpointOK")
            highLimitOK = d.data("boiler.highLimitController.highLimitOK")
            minimumRunTimeOK = d.data("boiler.minimumRunTimeController.minimumRunTimeOK")
            boilerActualEnable = d.data("boiler.enableSwitch.u2")  # Alternative: switch control signal
        except:
            print("Note: Could not find all control signals, some may not be displayed")
    # Get setpoint temperature (T_setpoint_F parameter, default 170°F)
    try:
        T_setpoint_F_param = d.data("boiler.T_setpoint_F")
        # Ensure it's a scalar (take first value if array)
        if isinstance(T_setpoint_F_param, np.ndarray):
            T_setpoint_F = float(T_setpoint_F_param[0]) if len(T_setpoint_F_param) > 0 else 170.0
        else:
            T_setpoint_F = float(T_setpoint_F_param)
    except:
        T_setpoint_F = 170.0  # Default 170°F if parameter not found

    # Get high limit temperature (highLimit_F parameter, default 180°F)
    try:
        highLimit_F_param = d.data("boiler.highLimit_F")
        # Ensure it's a scalar (take first value if array)
        if isinstance(highLimit_F_param, np.ndarray):
            highLimit_F = float(highLimit_F_param[0]) if len(highLimit_F_param) > 0 else 180.0
        else:
            highLimit_F = float(highLimit_F_param)
    except:
        # Default if not available
        highLimit_F = 180.0  # Default 180°F

    # Get minimum run time (t_min_run_sec parameter, default 60.0 seconds)
    try:
        t_min_run_sec_param = d.data("boiler.t_min_run_sec")
        if isinstance(t_min_run_sec_param, np.ndarray):
            t_min_run_sec = float(t_min_run_sec_param[0]) if len(t_min_run_sec_param) > 0 else 60.0
        else:
            t_min_run_sec = float(t_min_run_sec_param)
    except:
        t_min_run_sec = 60.0  # Default 60.0 seconds

except Exception as e:
    print(f"Error reading data: {e}")
    names = list(d.names())
    print(f"Available variables (first 30): {names[:30]}")
    # Try with full path
    try:
        enable = d.data("TanklessBoilers.Examples.SimpleBoilerTest.boiler.enable")
        Q_actual = d.data("TanklessBoilers.Examples.SimpleBoilerTest.boiler.Q_actual") / 1000
        T_inlet_K = d.data("TanklessBoilers.Examples.SimpleBoilerTest.boiler.T_inlet")
        T_outlet_K = d.data("TanklessBoilers.Examples.SimpleBoilerTest.boiler.T_outlet")
        T_inlet = (T_inlet_K - 273.15) * 9/5 + 32
        T_outlet = (T_outlet_K - 273.15) * 9/5 + 32
        m_flow_kg_s = d.data("TanklessBoilers.Examples.SimpleBoilerTest.boiler.m_flow")
        p_PSI = d.data("TanklessBoilers.Examples.SimpleBoilerTest.boiler.p_PSI")
        highLimitTripped_model = d.data("TanklessBoilers.Examples.SimpleBoilerTest.boiler.highLimitTripped")
        setpointOK = d.data("TanklessBoilers.Examples.SimpleBoilerTest.boiler.setpointController.setpointOK")
        highLimitOK = d.data("TanklessBoilers.Examples.SimpleBoilerTest.boiler.highLimitController.highLimitOK")
        minimumRunTimeOK = d.data("TanklessBoilers.Examples.SimpleBoilerTest.boiler.minimumRunTimeController.minimumRunTimeOK")
        boilerActualEnable = d.data("TanklessBoilers.Examples.SimpleBoilerTest.boiler.boilerEnableLogic.y")
        T_setpoint_F = float(d.data("TanklessBoilers.Examples.SimpleBoilerTest.boiler.T_setpoint_F")[0])
        highLimit_F = float(d.data("TanklessBoilers.Examples.SimpleBoilerTest.boiler.highLimit_F")[0])
        t_anti_short_cycle_min = float(d.data("TanklessBoilers.Examples.SimpleBoilerTest.boiler.t_anti_short_cycle_min")[0])
        t_min_run_sec = float(d.data("TanklessBoilers.Examples.SimpleBoilerTest.boiler.t_min_run_sec")[0])
        print("Successfully loaded with full path prefix")
    except Exception as e2:
        print(f"Error with full path: {e2}")
        sys.exit(1)

# Convert mass flow from kg/s to GPM
# 1 kg/s water ≈ 15.85 GPM (at standard conditions)
# 1 GPM = 0.0630902 kg/s, so 1 kg/s = 1/0.0630902 = 15.85 GPM
m_flow_gpm = m_flow_kg_s / 0.0630902

# Create plots - now 4 rows x 2 cols to add high limit plot
fig, axes = plt.subplots(4, 2, figsize=(14, 12))
fig.suptitle("SimpleBoilerTest Simulation Results", fontsize=16)

# Plot 1: Boiler control signals
ax = axes[0, 0]
# Plot individual control signals with dotted lines
if setpointOK is not None:
    ax.plot(time, setpointOK.astype(float), 'g:', linewidth=1.5, alpha=0.7, label='Setpoint OK')
if highLimitOK is not None:
    ax.plot(time, highLimitOK.astype(float), 'orange', linestyle=':', linewidth=1.5, alpha=0.7, label='High Limit OK')
if minimumRunTimeOK is not None:
    ax.plot(time, minimumRunTimeOK.astype(float), 'm:', linewidth=1.5, alpha=0.7, label='Min Run Time OK')
# External enable signal (dotted)
ax.plot(time, enable, 'b:', linewidth=1.5, alpha=0.7, label='External Enable')
# Actual boiler enable signal (solid line)
if boilerActualEnable is not None:
    ax.plot(time, boilerActualEnable.astype(float), 'r-', linewidth=2, label='Boiler Actual Enable')
else:
    # Fallback: try to use enableSwitch control signal
    try:
        boiler_switch = d.data("boiler.enableSwitch.u2")
        ax.plot(time, boiler_switch.astype(float), 'r-', linewidth=2, label='Boiler Actual Enable')
    except:
        ax.plot(time, enable, 'r-', linewidth=2, label='Boiler Enable (fallback)')
ax.set_ylabel("Status")
ax.set_ylim([-0.1, 1.1])
ax.set_xlabel("Time (s)")
ax.legend(loc='best', fontsize=8)
ax.grid(True, alpha=0.3)
ax.set_title("Boiler Control Signals")

# Plot 2: Heat output
ax = axes[0, 1]
ax.plot(time, Q_actual, 'r-', linewidth=2)
ax.set_ylabel("Heat Output (kW)")
ax.set_xlabel("Time (s)")
ax.grid(True, alpha=0.3)
ax.set_title("Boiler Heat Output")

# Plot 3: Temperatures
ax = axes[1, 0]
ax.plot(time, T_inlet, 'b-', label='Inlet', linewidth=2)
ax.plot(time, T_outlet, 'r-', label='Outlet', linewidth=2)
# Add setpoint and high limit lines (horizontal reference lines)
ax.axhline(y=T_setpoint_F, color='green', linestyle='--', linewidth=2, label=f'Setpoint ({T_setpoint_F:.1f}°F)')
ax.axhline(y=highLimit_F, color='orange', linestyle='--', linewidth=2, label=f'High Limit ({highLimit_F:.1f}°F)')
ax.set_ylabel("Temperature (°F)")
ax.set_xlabel("Time (s)")
ax.legend()
ax.grid(True, alpha=0.3)
ax.set_title("Water Temperatures")

# Plot 4: Temperature difference
ax = axes[1, 1]
delta_T = T_outlet - T_inlet
ax.plot(time, delta_T, 'g-', linewidth=2)
ax.set_ylabel("ΔT (°F)")
ax.set_xlabel("Time (s)")
ax.grid(True, alpha=0.3)
ax.set_title("Temperature Rise (Outlet - Inlet)")

# Plot 5: Mass flow rate
ax = axes[2, 0]
ax.plot(time, m_flow_gpm, 'c-', linewidth=2)
ax.set_ylabel("Flow Rate (GPM)")
ax.set_xlabel("Time (s)")
ax.grid(True, alpha=0.3)
ax.set_title("Primary Loop Flow Rate")

# Plot 6: Pressure
ax = axes[2, 1]
ax.plot(time, p_PSI, 'm-', linewidth=2)
ax.set_ylabel("Pressure (PSI)")
ax.set_xlabel("Time (s)")
ax.grid(True, alpha=0.3)
ax.set_title("Pressure After Pump")

# Plot 7: High Limit Status (inlet temp vs high limit)
ax = axes[3, 0]
ax.plot(time, T_inlet, 'b-', label='Inlet Temp', linewidth=2)
ax.axhline(y=highLimit_F, color='orange', linestyle='--', linewidth=2, label=f'High Limit ({highLimit_F:.1f}°F)')
# Highlight when high limit would be tripped (inlet >= highLimit)
high_limit_tripped = T_inlet >= highLimit_F
ax.fill_between(time, highLimit_F, T_inlet, where=high_limit_tripped, alpha=0.3, color='red', label='High Limit Tripped')
ax.set_ylabel("Temperature (°F)")
ax.set_xlabel("Time (s)")
ax.legend()
ax.grid(True, alpha=0.3)
ax.set_title("High Limit Monitoring (Inlet Temperature)")

# Plot 8: High Limit Trip Status (boolean)
ax = axes[3, 1]
if highLimitTripped_model is not None:
    high_limit_status = highLimitTripped_model.astype(float)
    ax.plot(time, high_limit_status, 'r-', linewidth=2, label='High Limit Tripped (model)')
else:
    high_limit_status = (T_inlet >= highLimit_F).astype(float)
    ax.plot(time, high_limit_status, 'r-', linewidth=2, label='High Limit Tripped (calculated)')
# Also show enable signal and boiler actual enable for reference
ax.plot(time, enable, 'g--', linewidth=1, alpha=0.5, label='Enable Input')
# Try to get the actual boiler enable signal if available
try:
    boiler_actual_enable = d.data("boiler.enableSwitch.u2")
    ax.plot(time, boiler_actual_enable.astype(float), 'b:', linewidth=1, alpha=0.7, label='Boiler Actual Enable')
except:
    pass
ax.set_ylabel("Status")
ax.set_ylim([-0.1, 1.1])
ax.set_xlabel("Time (s)")
ax.legend()
ax.grid(True, alpha=0.3)
ax.set_title("High Limit Trip Status & Boiler Enable")

plt.tight_layout()

# Save plot (next to the MAT file or in build directory)
if len(sys.argv) > 1:
    output_file = Path(sys.argv[1]).with_suffix('.png').with_name('simple_boiler_test.png')
else:
    build_dir = Path(__file__).parent.parent.parent / "build"
    output_file = build_dir / "simple_boiler_test.png"
plt.savefig(output_file, dpi=150, bbox_inches='tight')
print(f"\nPlot saved to: {output_file}")

# Print summary statistics
print("\n" + "="*60)
print("Summary Statistics:")
print("="*60)
print(f"Simulation time: {time[-1]:.1f} s ({time[-1]/60:.1f} minutes)")
print(f"\nHeat Output:")
print(f"  Max: {np.max(Q_actual):.2f} kW")
print(f"  Mean (when enabled): {np.mean(Q_actual[enable > 0.5]):.2f} kW" if np.any(enable > 0.5) else "  Mean (when enabled): N/A (never enabled)")
print(f"\nTemperatures:")
print(f"  Inlet - Min: {np.min(T_inlet):.1f}°F, Max: {np.max(T_inlet):.1f}°F, Mean: {np.mean(T_inlet):.1f}°F")
print(f"  Outlet - Min: {np.min(T_outlet):.1f}°F, Max: {np.max(T_outlet):.1f}°F, Mean: {np.mean(T_outlet):.1f}°F")
print(f"  ΔT - Max: {np.max(delta_T):.1f}°F, Mean: {np.mean(delta_T):.1f}°F")
print(f"\nFlow Rate:")
print(f"  Mean: {np.mean(m_flow_gpm):.2f} GPM")
print(f"  Max: {np.max(m_flow_gpm):.2f} GPM")
print(f"\nPressure:")
print(f"  Mean: {np.mean(p_PSI):.2f} PSI")
print(f"  Max: {np.max(p_PSI):.2f} PSI")
print(f"\nSetpoint:")
print(f"  Setpoint: {T_setpoint_F:.1f}°F")
print(f"  Inlet Min: {np.min(T_inlet):.1f}°F, Max: {np.max(T_inlet):.1f}°F")
print(f"\nHigh Limit:")
print(f"  High Limit: {highLimit_F:.1f}°F")
print(f"  Inlet Max: {np.max(T_inlet):.1f}°F")
high_limit_tripped_time = np.sum(high_limit_status > 0.5) * (time[-1] / len(time))
if highLimitTripped_model is not None:
    print(f"  High limit tripped for: {high_limit_tripped_time:.1f} s ({high_limit_tripped_time/60:.1f} min) [from model]")
else:
    print(f"  High limit tripped for: {high_limit_tripped_time:.1f} s ({high_limit_tripped_time/60:.1f} min) [calculated]")
print(f"\nMinimum Run Time:")
print(f"  Minimum Run Time: {t_min_run_sec:.1f} s ({t_min_run_sec/60:.1f} min)")

plt.show()
